### ISSUE TITLE
Gestion des dépendances

### ISSUE THREAD

**Issue by ThomasSoeiro** [strayMat/sndsTools#18]
Je suis surpris de voir :

https://github.com/strayMat/paresnds/blob/a429f47f6839432b5d7933f5b027924b4f564ac5/DESCRIPTION#L6-L14

Mais pas de `import()`/`importFrom()` dans le NAMESPACE et peu de `::` dans le code.

Je propose d'utiliser la [méthode recommandée dans _R Packages_](https://r-pkgs.org/dependencies-in-practice.html) `paquet::function()` dans le code (voir aussi [Writing R Extensions](https://cran.r-project.org/doc/manuals/R-exts.html#Specifying-imports-and-exports)). On y verra plus clair et on pourra probablement reconsidérer certaines dépendances.

(Je n'ai pas encore testé : est-ce que le paquet et installable et passe `R CMD check --as-cran` ?)

**Comment by strayMat** [comment]
Effectivement, le code tel qu'il est dans le commit initial ne respecte pas les bonnes pratiques d'imports mais c'est le cas pour les fonctions bien documentées et réécrites des PRs d'Antoine (https://github.com/strayMat/paresnds/pull/7 et https://github.com/strayMat/paresnds/pull/6). 

Reste à faire la même chose pour les autres fonctions existantes : cf. issue sur la doc, https://github.com/strayMat/paresnds/issues/1

Le paquet passe un [`devtools::check(error_on="error")`](). Mais ce serait pas mal de mettre cette commande de check dans une CI pour chaque PR (comme ça, on ne laisse pas passer dans la branche principale du code qui n'est pas cran compatible). J'ai ajouté une issue en ce sens (https://github.com/strayMat/paresnds/issues/24) et je regarderai comment faire cet été si j'ai le temps.

**Comment by strayMat** [comment]
Je ferme. Toutes les fonctions utilisent désormais le prefix `package::function`
