### ISSUE TITLE
Filtre CPL_MAJ_TOP < 2

### ISSUE THREAD

**Issue by ThomasSoeiro** [strayMat/sndsTools#23]
cf le support de la Cnam "Formation Données Individuelles Bénéficiaires (accès permanent) exhaustives et échantillonnées" (chemin d'accès sur le portail : `SNIIRAM/_Documentation SNIIRAM- SNDS/Formations/supports des formations SNIIRAM/7-Données Individuelles Bénéficiaires - accès permanent/Formation DIB - Avril 2024`) à partir de la diapo 116 :
![image](https://github.com/user-attachments/assets/40317273-338a-4982-bf7f-b46e2512a822)

**Comment by strayMat** [comment]
Ce filtre est désormais pris en compte dans extract_drug_dispenses.R et extract_consultations_erprsf.R

Merci beaucoup pour le pointeur ainsi que la référence ! :D 

Idéalement, il faudrait que l'on documente ces choix dans la doc et dans le code mais je fais une issue distincte à ce sujet.

**Comment by strayMat** [comment]
J'ai ajouté les filtres dans la fonction extract_drug_dispense.R 

Pour la documentation, je refère à l'issue #46  laissée ouverte. Ce n'est pas immédiat car les documents de la CNAM ne sont pas sur internet donc un simple lien url ne suffit pas pour documenter proprement ces filtres.

**Comment by ThomasSoeiro** [comment]
Uhm pour le coup il me semble que ce filtre est inutile pour les médicaments. Faudrait tester (voire demander confirmation à la Cnam).

**Comment by strayMat** [comment]
Effectivement, je supprime le filtre et ferme l'issue (cf. https://documentation-snds.health-data-hub.fr/snds/fiches/sas_prestation_dcir.html#recommandations-pour-les-requetes)
