### ISSUE TITLE
Nom du paquet

### ISSUE THREAD

**Issue by ThomasSoeiro** [strayMat/sndsTools#25]
Si on diffuse, est-ce que le nom `{paresnds}` est judicieux ?
- Le nom ne me semble pas indiquer clairement à quoi s'attendre.
- D'après le fichier `paresnds/pathologies-retrieval-snds.Rproj`, c'est l'abreviation de _pathologies retrieval_ ? Ca me semble un peu restrictif : on peut extraire les médicaments et on envisage de proposer de quoi créer un référentiel bénéficiaires, voire plus à l'avenir. Et c'est du franglais.

Autres suggestions : snds-extractor, easy-snds, snds-r...

**Comment by strayMat** [comment]
Oui c'était un nom d'attente. 

J'aime bien sndsExtractor ou sndsExtracteur. Je préférerai en plus compact, sndsExtract ([je crois que R a une convention camelCase pour les noms de package donc _ est interdit et pas sûr que ](https://stackoverflow.com/questions/24201568/what-constitutes-a-good-package-name-according-to-cran). 

Est-ce que quelqu'un a d'autres suggestions ? 

Sinon je peux me charger en fin de semaine de renommer le paquet et le github :)

**Comment by ThomasSoeiro** [comment]
`snds_tools` ou `sndsTools` selon la convention ? (Si on ajoute des fonctions pour créer un référentiel patient ça relève moins de l'extraction.)

**Comment by strayMat** [comment]
Done. J'ai poussé un peu comme un boeuf sur la main branch le changement de nom. J'en ai profité pr ajouter @ThomasSoeiro dans les contributeurs ;)
