### ISSUE TITLE
Tables prescription archivées et le mois de décembre

### ISSUE THREAD

**Issue by MarcDibling** [strayMat/sndsTools#26]
Hello 👋,

Sauf erreur de ma part, pour les tables archivées de prestation, une majeure partie des prestations exécutées en décembre d’une année A sont retrouvées dans la table de l’année A+1. 

Petite représentation, longue mais flagrante, basée sur l’exemple du notebook pour confirmer la couverture partiellement exhaustive :

```r
start_date <- as.Date("2011-11-01")
end_date <- as.Date("2015-01-01")
atc_cod_starts_with <- c("N04A")

dispenses <- extract_drug_dispenses(
    start_date = start_date,
    end_date = end_date,
    atc_cod_starts_with = atc_cod_starts_with)

dispenses %>%
  ggplot(aes(x = EXE_SOI_DTD, y = BEN_NIR_PSA)) +
  geom_point(size = 0.0001, alpha = 0.1) +
  theme(axis.text.y = element_blank())
```
Chaque point noir correspond à une date de délivrance et le problème concerne uniquement les transitions avec les tables archivées. Les bandes blanches indiquent donc que les prestations de décembre n'ont pas été récupérées. 
![Screenshot 2024-08-01 at 19 29 38](https://github.com/user-attachments/assets/47f7c7c6-bdf5-43be-abb8-f8103580a898)

Il s’agit d’un problème particulièrement embêtant parce qu’il nécessite une requête de la table de l'année A MAIS AUSSI celle de A+1 à chaque itération pour pouvoir être exhaustif sur l’année A. 

Aussi, l’utilisation de “≤” dans les flux peut engendrer des doublons dans l’éventualité où FLX_DIS_DTD tombe sur 1er janv. Je ne sais pas si cela arrive fréquemment mais la modification est simple et l’impact non négligeable car peut permettre de libérer de l’espace sans stocker les doublons. 

Je vais proposer des modifs de ce code pour prendre en compte ces prestations oubliées mais aussi spécifier la granularité (mois ou années) de la période de flux afin d’obtenir une barre de chargement plus dynamique. 

PS : génial le travail déjà réalisé !

-Marc Dibling

**Comment by abelloir-zz** [comment]
Hello Marc, merci beaucoup d'avoir pris le temps de décrire le problème ! Il y a effextivement une erreur sur les filtres, je pense que modifier le filtre sur `EXE_SOI_DTD` au sein de la boucle suffit (pas besoin d'introduire une boucle en plus) : tout en gardant le filtre qui exige que `FLX_DIS_DTD` soit au sein de l'année courante, il faut juste remplacer le filtre qui impose que `EXE_SOI_DTD` soit au sein  de l'année courante par un filtre qui exige que `EXE_SOI_DTD` soit entre les dates de début et de fin d'extraction globales (start_date et end_date)
