### ISSUE TITLE
C et CS uniquement dans les ACE ?

### ISSUE THREAD

**Issue by GuillaumePressiat** [strayMat/sndsTools#27]
Bonjour,

Juste pour y penser je vois qu'il y a un filtre uniquement sur les codes NGAP C et CS dans le code ici : 

https://github.com/strayMat/paresnds/blob/main/R/retrieve_ace.R#L35

Je n'ai pas finalisé ma formation SNDS encore, reste le 2ème morceau à faire mais dans ce qu'on envoie des hôpitaux il y a bien d'autres codes NGAP dans les RSF-ACE pour les consultations, de tout types, (APU, APC, APY, APV, G, et bien d'autres encore). La colonne interrogée ici est peut-être un agrégat ?

Bref => il y a un aspect fort sur les nomenclatures à aborder j'imagine et j'ouvre ce ticket uniquement pour penser à en parler (fut un temps on en avait parlé avec @pajachiet mais cela faisait beaucoup pour [nomensland](https://github.com/GuillaumePressiat/nomensland/issues/1), depuis il y a eu le SMT etc.)

Gp

**Comment by strayMat** [comment]
Bien vu! Je pense que c'était le code initial d' @abelloir-zz qui s'intéressait uniquement aux C et CS. Il faudrait mettre ce filtre en paramètre effectivement. 
J'ai commencé à bien nettoyer et documenter cette fonction dans la branche [unit-test](https://github.com/strayMat/paresnds/blob/unit-test/R/extract_hospital_consultations.R#L55C3-L55C26). Je vais changer pour mettre l'act cod en paramètre et renvoyer à la nomenclature sur le dico et à l'article sur la [documentation du SNDS](https://documentation-snds.health-data-hub.fr/snds/fiches/actes_consult_externes.html#annexe).

Si quelqu'un se sent de revoir cette PR, je suis preneur pr pouvoir la merger d'ailleurs :) https://github.com/strayMat/paresnds/pull/12

**Comment by GuillaumePressiat** [comment]
Ok, merci de ce retour rapide !

Dans la foulée, en mode mémo, je ne sais pas non plus si ce ACT_COD contient les majorations de féries et les nuits mais d'après le lien que tu indiques sur la doc SNDS c'est le cas.


On peut donc avoir sur 5 caractères :


```text
C    
CS   
CS  F
CS  N
G   N
G   F
```

dans la colonne je crois ?

donc une particularité à prendre en compte d'une manière ou d'une autre dans le code qui interroge la colonne car le plus souvent, on néglige cet aspect factu quand on fait de la recherche et finalement on s'intéresse plutôt au trim des 4 premiers caractères ?

**Comment by strayMat** [comment]
Oui c'est possible. Je ne vois pas trop comment prendre cela en compte. Je pense que selon les besoins de l'utilisateur, il peut être intéressé par les majorations ou non. C'est à lui de choisir à partir de la liste des codes prestations non ? As -tu une meilleure idée ? 

Pour l'instant j'ai renvoyé à la page de la documentation sur les actes et consultations externes dans la doc de la fonction [`extract_hospital_consultations`](https://github.com/strayMat/paresnds/blob/22af49d0cedad9ba6acc291bb1bba5e8f3ad4ca2/R/extract_hospital_consultations.R#L18).

**Comment by strayMat** [comment]
Je ferme, j'ai l'impression que le pb principal sur les filtres du code prestation a été réglé. 
Quitte à rouvrir si on trouve une meilleure solution pour sortir l'info sur les majorations. Mais je ne suis pas au clair sur le besoin.
