### ISSUE TITLE
Fichier doublon pour l'extraction des médicaments

### ISSUE THREAD

**Issue by strayMat** [strayMat/sndsTools#35]
Il me semble que dans la version actuelle du code on a un doublon pour la fonction d'extraction des médicaments : 

- https://github.com/strayMat/sndsTools/blob/main/R/retrieve_atc.R : l'ancienne fonction d'extraction
- https://github.com/strayMat/sndsTools/blob/main/R/extract_drug_dispenses.R  : la nouvelle fonction documentée de la PR (https://github.com/strayMat/sndsTools/pull/6)

Est-ce que je me trompe et ces fonctions sont complémentaires ?

**Comment by abelloir-zz** [comment]
C'est effectivement la même fonction, ça a du arriver lors d'un rebase je n'ai pas fait attention ! je supprime l'ancienne dans ma prochaine PR

**Comment by strayMat** [comment]
Top !

**Comment by strayMat** [comment]
C'est réglé ! Merci pour la PR https://github.com/strayMat/sndsTools/pull/34 Antoine ! Je ferme
