### ISSUE TITLE
Ajout de principes de gouvernances

### ISSUE THREAD

**Issue by strayMat** [strayMat/sndsTools#36]
L'idée est plus de se donner nous même des guides pour fonctionner de façon fluide que d'inscrire des règles dans le marbre. 
Qu'en pensez-vous ? 

Quelques documents dont on pourrait s'inspirer : 
- https://scikit-learn.org/stable/governance.html
- https://code-review.tidyverse.org/collaboration/
- https://github.com/pandas-dev/pandas/blob/main/web/pandas/about/governance.md

**Comment by abelloir-zz** [comment]
Ca sera nécessaire effectivement quand il y aura plus de monde sur le projet ! Pour l'instant on peut attendre un peu non ?

**Comment by strayMat** [comment]
C'est sûrement un peu tôt. Mais je peux quand même essayer de proposer un truc très simple qui marche déjà pour nous et qui donne un peu la philosophie du projet. 

Par exemple : 

```
Cet effort de développement d'un paquet R pour les données du SNDS est un projet communautaire basé sur le consensus et l'investissement. N'importe qui ayant un intérêt dans le projet peut rejoindre la communauté, contribuer au projet et à ses orientations futures. Ce document précise comment la participation a lieu, comment trouver / gagner sa place dans le projet, et quels sont les différents rôles et responsabilités. 

Actuellement, le paquet essaye de fonctionner avec deux types de contributeurs : 

## Les contributeurs 

Les contributeurs  classiques faisant des issues, des reviews et des propositions de nouvelles fonctionnalités  (pull requests). Chaque nouvelle fonctionnalité avant d'être intégré doit être revue par un core contributeur

## Les core contributeurs 

Les core contributors sont particulièrement investis dans le projet. Ils ont des accès larges sur le dépôt. Ce sont eux seulement qui valide l'intégration de nouvelles fonctionnalités (pull requests) et peuvent fermer les issues. 

## Devenir un contributeur  

N'importe qui peut être contributeur en faisant [une nouvelle issue](), une pull request, ou en effectuant une revue sur une pull request existante.  Le [guide de contribution]() détaille les différentes manières de contribuer. 

## Devenir un core contributeur

Après une ou deux pull requests ou reviews de la part d'un nouveau contributeur, sur demande de ce dernier, les core contributeurs décident collégialement de l'intégrer au projet. Le nombre de core contributeur n'est pas limité. Le projet est en phase très précoce, et accueille à bras ouverts de nouveaux core contributeurs 🤗. 
```

**Comment by ThomasSoeiro** [comment]
Ca me semble important puisque le but est de diffuser ! Ok pour cette version.

@strayMat Tu suggérais de déménager le projet quand on l'officialiserait. Ca me semble préférable de continuer à l'héberger sur ton compte (ou celui de @abelloir-zz bien sûr). Vous êtes les initiateurs du projet, vous êtes les plus légitimes. Ces principes de gouvernance légitimisent cela encore plus à mon avis. Et je trouve que c'est très bien que la communauté d'appuie sur différents acteurs plutôt que tout soit centralisé.

**Comment by strayMat** [comment]
Merci pour le retour :) 
Ok pr ne pas le déménager mtnt. Je me disais que créer une organisation github dédiée pourrait plus simple pour la gestion des droits, mais on pourra faire ça plus tard si on est gêné par l'hebergement sur un github perso.

**Comment by ThomasSoeiro** [comment]
Ah j'avais pas compris que tu pensais à une organisation github indépendante. Bonne idée du coup ! (J'étais pas emballé car j'avais compris que tu pensais à un déménagement vers le HDH ou la CNAM.)
