### ISSUE TITLE
R and SQL coding style

### ISSUE THREAD

**Issue by ThomasSoeiro** [strayMat/sndsTools#41]
Pour R, je propose le [tidyverse style guide](https://style.tidyverse.org/index.html).

Pour SQL, je propose le [Mozilla SQL Style Guide](https://docs.telemetry.mozilla.org/concepts/sql_style).

**Comment by strayMat** [comment]
Très bien pour les deux. 

Simplement, j'ai l'impression que le tidyverse ne mentionne pas le pipe natif `|>` mais le pipe `%>%` (cf. [Pipes](https://style.tidyverse.org/pipes.html)). Est-ce grave? 

Je m'occupe d'ajouter ça au contributing.md avant de merger https://github.com/strayMat/sndsTools/pull/38

**Comment by ThomasSoeiro** [comment]
> Très bien pour les deux.
> 
> Simplement, j'ai l'impression que le tidyverse ne mentionne pas le pipe natif `|>` mais le pipe `%>%` (cf. [Pipes](https://style.tidyverse.org/pipes.html)). Est-ce grave?

Bien vu ! Ce n'est qu'une question de temps (cf tidyverse/style#182). Je propose d'utiliser le pipe natif de toutes façons.

**Comment by strayMat** [comment]
Ingtégré à #38 ([lien vers le changement](https://github.com/strayMat/sndsTools/blob/d3d10700307836cef90e2f6392d56f68ed776a77/vignettes/contribuer.Rmd#L48)
