### ISSUE TITLE
Rajouter des barres de chargement pour les extractions

### ISSUE THREAD

**Issue by abelloir-zz** [strayMat/sndsTools#5]
En l'état, aucune visibilité n'est donnée à l'utilisateur sur l'exécution des fonctions d'extraction qui répètent des requêtes sur plusieurs  années. Une barre de progression avec un temps de fin estimé serait un minimum. Dans un second temps, il faudrait implémenter un système de logging pour les extractions.

**Comment by strayMat** [comment]
A part de voir la progression, quel est l'intérêt de boucler sur les années ?

**Comment by abelloir-zz** [comment]
Pour le DCIR, le découpage par année me semble nécessaire au moins pour les tables ER_PRS_F archivées parce que celles-ci portent un nom différent par année (à moins de regrouper toutes les tables ER_PRS_F en amont ?). C'est pour cela que j'avais fais une boucle sur les années, avec le bonus d'avoir de la visibilité avec la barre de progression sur requêtes qui peuvent être très longues pour les délivrances de médicaments (de l'ordre de l'heure).
Mais en effet il faudrait tester de faire la requête d'extraction des délivrances de médicaments (une des plus longues) pour des années non archivées sur ER_PRS_F en entier, pour vérifier qu'itérer sur les années ne rallonge pas l'exécution excessivement. Je m'occupe de faire un micro benchmark sur le sujet

**Comment by strayMat** [comment]
Il me semble que cette feature a été implementé (dans extract_consultations_erprsf, extract_drug_dispenses, extract_hospital_consultations). Je ferme donc l'issue. La présence d'une barre de progression est cependant à mettre quand on documentera l'API : #32
